name: hello

on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: python-setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: run-script
        run: python PRAC-1.py
