name: C

oon: null
  push: null
    branches: master
     pull: null
       branches: master

jobs:
  result:
    runs-on: ubuntu-latest

    steps:
    - name: output
      run: python PRAC-1.py

      
